language: node_js

os:
  # - windows
  - linux
  - osx

node_js:
  - "lts/*"
  - "10"
  - "8"
  - "6"

script:
  # Lint Code
  - "npm run lint"
  - "npm run test"
  # Build Module Start
  - "npm run clean"
  - "npm run build"
  - "npm run resource"
  # Build Module End
  # Test Module
  - "rm -r node_modules"
  - "npm install --production"
  - "node . -h"
  - "node . new .script_test"

after_success:
  - "npm install nyc --global"
  - "npm install coveralls@~3.0.0 --global"
  - "nyc npm test"
  - "nyc report --reporter=text-lcov | coveralls"

before_deploy:
  - "rm -r node_modules"
  - "npm install"
  - "npm run clean"
  - "npm run build:prod"
  - "npm run resource"

deploy:
  skip_cleanup: true
  provider: npm
  email: "arylo.open+npm@gmail.com"
  api_key: "${NPM_TOKEN}"
  on:
    branch: master
    node_js: "lts/*"

after_deploy:
  - "npx arylo-init new .deploy_test"
  - "npm run test .deploy_test"
  - "npm install -g arylo-init"
  - "arylo-init -h"
