language: node_js

os:
  # - windows
  - linux
  - osx

node_js:
  - "lts/*"
  - "10"
  - "8"
  - "6"

before_script:
  - "npm install nyc --global"
  - "npx -h || npm install npx --global"

before_deploy:
  - "rm -rf node_modules"
  - "npm install"
  - "npm run clean"
  - "npm run build:prod"
  - "npm run resource"

stages:
  - lint
  - test
  - test-prod
  - deploy
  - new module test

jobs:
  include:
    - stage: lint
      node_js: "lts/*"
      os: linux
      script:
        - "npm run lint"
    - &test
      stage: test
      script:
        - "npm install"
        - "nyc npm run test"
      after_success:
        - "npm install coveralls@~3.0.0 --global"
        - "nyc report --reporter=text-lcov | coveralls"
    - stage: test-prod
      node_js: "lts/*"
      os: linux
      script:
        - "npm install"
        - "npm run clean && npm run build:prod && npm run resource"
        - "rm -rf node_modules"
        - "npm install --production"
        - "node . -h"
        - "node . new .script_test"
    - stage: deploy
      script: skip
      node_js: "lts/*"
      os: linux
      deploy:
        skip_cleanup: true
        provider: npm
        email: "arylo.open+npm@gmail.com"
        api_key: "${NPM_TOKEN}"
        on:
          branch: master
    - stage: new module test
      script:
        - "npx arylo-init new .deploy_test"
        - "npm run test .deploy_test"
        - "npm install -g arylo-init"
        - "arylo-init -h"
    - <<: *test
      stage: new module test
