language: node_js

node_js:
  - "node"
  - "lts/*"
  - "8"
  - "6"

script:
  - "npm run lint"
  - "npm run build"
  - "node ./scripts/copy"
  - "rm -r node_modules"
  - "npm install --production"
  - "node . -h"
  - "node . new .script_test"
  - "ls -al .script_test/*"

before_deploy:
  - "npm install"
  - "npm run clean"
  - "npm run tsc -- -P ./tsconfig.prod.json"
  - "node ./scripts/copy"

deploy:
  skip_cleanup: true
  provider: npm
  email: "arylo.open@gmail.com"
  api_key: "${NPM_TOKEN}"
  on:
    branch: master
    node_js: "node"

after_deploy:
  - "npx arylo-init new .deploy_test"
  - "ls -al .deploy_test/*"
  - "npm install -g arylo-init"
  - "arylo-init -h"